# Site settings
title: AllenYang
header-img: "img/cover.jpg"
tagline: "cn"  
description: "杨亚洲|读而立·写而生"  
baseurl: ""
url: "http://allenyang.cn"  

# About/contact
owner: 
  name: " AllenYang"
  email: "allenyang1995@outlook.com"
  bio: "写就是写的报酬"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  
linkedin_username: 亚洲-杨-130a68114?trk=navINMTIN_responsive_tab_profile
github_username: allenyangfly
facebook_username: 
weibo_username: allenyangfly 
zhihu_username: yang-ya-zhou-6
stackoverflow_username: allenyang

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Haerbin

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AllenYang"
      header-img: "img/facebook.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : AllenYang
  disqus :
      short_name : AllenYang

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
